### PR TITLE
correctly implement whitespace trimming in sanitizePath

### PR DESCRIPTION
**Pull request by talhoid**
This fixes a regression introduced by #215.

#215 did not successfully trim the whitespace. It assigns a new variable with a trimmed version of the string, but it never uses it for further sanitization. This also causes an error during compilation as the variable is unused:

```
    > tsc -b && vite build

    src/lib/utils.ts(12,7): error TS6133: 'sanitized' is declared but its value is never read.
     ELIFECYCLE  Command failed with exit code 2.
```

### CODE REVIEW

**Comment by afkarxyz** [comment]
I have already fixed it locally
